// Generates the Arabic→English translation map for psl_video_service.dart.
//
// Strategy: every English token from the PSL dictionary that has a clip
// gets one or more Arabic surface forms. Multiple Arabic forms collapsing
// to the same English token is fine — they all resolve to the same clip.
//
// Run:  node scripts/generate_psl_arabic_map.js > arabic_map.txt
//       (then paste into psl_video_service.dart)
//
// Manually-curated translation table. Pakistani-specific proper nouns
// are intentionally omitted because no Arabic translation exists.

const fs = require('fs');
const tokens = fs
  .readFileSync(__dirname + '/../psl-tokens.txt', 'utf8')
  .split('\n')
  .map((s) => s.trim())
  .filter(Boolean);

// English token → Arabic form(s). Multiple Arabic = multiple keys → same target.
const T = {
  // ── numbers
  one: ['واحد', 'احد'],
  two: ['اثنان', 'اثنين', 'اتنين'],
  three: ['ثلاثة', 'ثلاث'],
  four: ['اربعة', 'أربعة', 'اربع'],
  five: ['خمسة', 'خمس'],
  six: ['ستة', 'ست'],
  seven: ['سبعة', 'سبع'],
  eight: ['ثمانية', 'ثمان', 'تمانية'],
  nine: ['تسعة', 'تسع'],
  ten: ['عشرة', 'عشر'],
  'a hundred': ['مئة', 'مائة'],
  'one hundred': ['مئة', 'مائة'],
  'five hundred': ['خمسمائة', 'خمسمئة'],
  'a thousand': ['الف', 'ألف'],
  'one thousand': ['الف', 'ألف'],
  'ten thousand': ['عشرة آلاف', 'عشرة الاف'],
  'one lakh': ['مئة الف'],
  'one crore': ['عشرة ملايين'],

  // ── family / people
  father: ['اب', 'أب', 'والد', 'ابي'],
  papa: ['بابا', 'بابي'],
  dad: ['بابا'],
  daddy: ['بابا'],
  mother: ['ام', 'أم', 'والدة', 'امي'],
  mom: ['ماما'],
  mommy: ['ماما'],
  mama: ['ماما'],
  brother: ['اخ', 'أخ', 'اخي'],
  sister: ['اخت', 'أخت', 'اختي'],
  son: ['ابن', 'ولد'],
  daughter: ['ابنة', 'بنت'],
  boy: ['ولد', 'صبي'],
  girl: ['بنت', 'فتاة'],
  child: ['طفل'],
  baby: ['رضيع', 'بيبي'],
  family: ['عائلة', 'اسرة', 'أسرة'],
  friend: ['صديق', 'صاحب'],
  husband: ['زوج'],
  wife: ['زوجة'],
  woman: ['امرأة', 'مرأة', 'ست'],
  lady: ['سيدة'],
  female: ['أنثى', 'انثى'],
  male: ['ذكر'],
  feminine: ['مؤنث'],
  masculine: ['مذكر'],
  gentleman: ['رجل محترم'],
  'old man': ['رجل عجوز', 'عجوز'],
  'old woman': ['امراة عجوزة', 'عجوزة'],
  'elderly man': ['رجل مسن'],
  'elderly woman': ['امرأة مسنة'],
  manly: ['رجولي'],
  people: ['ناس'],
  he: ['هو'],
  she: ['هي'],
  we: ['نحن', 'احنا'],
  they: ['هم'],
  me: ['انا', 'أنا'],
  this: ['هذا', 'دا', 'هذه'],
  that: ['ذلك', 'تلك'],
  here: ['هنا'],
  there: ['هناك'],
  who: ['من'],
  whom: ['من'],
  whose: ['لمن'],
  what: ['ماذا', 'ايه'],
  when: ['متى', 'امتى'],
  // ── relatives (extended)
  'maternal grandfather': ['جد لام'],
  'maternal grandmother': ['جدة لام'],
  'paternal grandfather': ['جد لاب'],
  'paternal grandmother': ['جدة لاب'],
  "brother's son": ['ابن الاخ'],
  "brother's daughter": ['بنت الاخ'],
  "brother's wife": ['زوجة الاخ'],
  "sister's son": ['ابن الاخت'],
  "sister's daughter": ['بنت الاخت'],

  // ── time
  day: ['يوم'],
  night: ['ليل'],
  morning: ['صباح'],
  evening: ['مساء'],
  noon: ['ظهر'],
  afternoon: ['بعد الظهر'],
  today: ['اليوم'],
  tomorrow: ['غدا', 'بكرة'],
  'day after tomorrow': ['بعد غد', 'بعد بكرة'],
  yesterday: ['امس', 'أمس', 'مبارح'],
  week: ['اسبوع', 'أسبوع'],
  month: ['شهر'],
  year: ['سنة', 'عام'],
  hour: ['ساعة'],
  'half hour': ['نصف ساعة'],
  'half an hour': ['نصف ساعة'],
  time: ['وقت', 'زمن'],
  'time off': ['اجازة'],
  holiday: ['عطلة', 'اجازة'],
  monday: ['الاثنين', 'الاتنين'],
  tuesday: ['الثلاثاء'],
  wednesday: ['الاربعاء', 'الأربعاء'],
  thursday: ['الخميس'],
  friday: ['الجمعة'],
  saturday: ['السبت'],
  sunday: ['الاحد', 'الأحد'],
  january: ['يناير'],
  february: ['فبراير'],
  march: ['مارس'],
  april: ['ابريل', 'أبريل'],
  may: ['مايو'],
  june: ['يونيو'],
  july: ['يوليو'],
  august: ['اغسطس'],
  september: ['سبتمبر'],
  october: ['اكتوبر'],
  november: ['نوفمبر'],
  december: ['ديسمبر'],
  before: ['قبل'],
  // 'previous' uses same sign as 'before' arguably
  previous: ['سابق'],
  early: ['مبكر'],
  late: ['متأخر'],
  next: ['بعد', 'التالي'],
  again: ['مرة اخرى', 'تاني'],
  always: ['دائما'],
  forever: ['للأبد', 'للابد'],
  ever: ['ابدا'],
  every: ['كل'],
  annual: ['سنوي'],
  annually: ['سنويا'],
  yearly: ['سنوي'],
  monthly: ['شهري'],
  // seasons
  summer: ['صيف'],
  winter: ['شتاء'],
  autumn: ['خريف'],
  // weather
  weather: ['طقس', 'جو'],
  hot: ['حار', 'حر'],
  cold: ['بارد', 'برد'],
  warm: ['دافئ'],
  rain: ['مطر', 'مطره'],
  rainfall: ['امطار'],
  raining: ['تمطر'],
  rainy: ['ممطر'],
  storm: ['عاصفة'],
  stormy: ['عاصف'],
  hailstorm: ['عاصفة برد'],
  'wind storm': ['عاصفة رياح'],
  rainbow: ['قوس قزح'],
  sun: ['شمس'],
  sunny: ['مشمس'],
  moon: ['قمر'],
  stars: ['نجوم'],
  sky: ['سماء'],

  // ── places / nature
  house: ['بيت', 'منزل'],
  home: ['بيت', 'منزل'],
  bathroom: ['حمام'],
  toilet: ['تواليت', 'مرحاض'],
  washroom: ['حمام'],
  kitchen: ['مطبخ'],
  hospital: ['مستشفى'],
  school: ['مدرسة'],
  classroom: ['فصل'],
  college: ['كلية'],
  university: ['جامعة'],
  library: ['مكتبة'],
  mosque: ['مسجد', 'جامع'],
  masjid: ['مسجد'],
  shrine: ['ضريح'],
  graveyard: ['مقبرة'],
  cemetery: ['مقبرة'],
  market: ['سوق'],
  shop: ['محل', 'دكان'],
  bookshop: ['مكتبة'],
  bookstore: ['مكتبة'],
  hotel: ['فندق'],
  restaurant: ['مطعم'],
  museum: ['متحف'],
  garden: ['حديقة'],
  park: ['حديقة'],
  forest: ['غابة'],
  jungle: ['غابة'],
  zoo: ['حديقة حيوان'],
  river: ['نهر'],
  sea: ['بحر'],
  ocean: ['محيط'],
  mountain: ['جبل'],
  mountains: ['جبال'],
  mountainous: ['جبلي'],
  hills: ['تلال'],
  hilly: ['تلي'],
  road: ['طريق', 'شارع'],
  street: ['شارع'],
  streets: ['شوارع'],
  village: ['قرية'],
  city: ['مدينة'],
  country: ['دولة', 'بلد'],
  province: ['محافظة'],
  provincial: ['محافظ'],
  continent: ['قارة'],
  world: ['عالم'],
  area: ['منطقة'],
  place: ['مكان'],
  location: ['موقع'],
  locality: ['منطقة'],
  residence: ['اقامة'],
  earth: ['ارض', 'أرض'],
  airport: ['مطار'],
  airfield: ['مطار'],
  hostel: ['نزل'],
  factory: ['مصنع'],
  office: ['مكتب'],
  workplace: ['مكان عمل'],
  bank: ['بنك'],
  'post office' : ['مكتب بريد'],
  stadium: ['ملعب'],
  fort: ['قلعة'],
  fortress: ['قلعة'],
  castle: ['قصر'],
  tomb: ['ضريح'],
  // station / transport hubs
  'bus stop': ['موقف باص'],
  'bus stand': ['موقف باص'],
  'bus station': ['محطة باص'],
  busstop: ['موقف باص'],
  'railway station': ['محطة قطار'],
  'train station': ['محطة قطار'],

  // ── transport
  car: ['سيارة', 'عربية'],
  bus: ['باص', 'اوتوبيس'],
  motorbike: ['دراجة نارية', 'موتوسيكل'],
  motorcycle: ['دراجة نارية'],
  rickshaw: ['تكتك'],
  van: ['فان'],
  tractor: ['جرار'],
  airplane: ['طائرة'],
  aeroplane: ['طائرة'],
  aircraft: ['طائرة'],
  'fighter jet': ['طائرة مقاتلة'],
  'military aircraft': ['طائرة عسكرية'],
  marine: ['بحري'],
  transportation: ['نقل', 'مواصلات'],
  'donkey carriage': ['عربة حمار'],
  'donkey cart': ['عربة حمار'],
  'donkey chariot': ['عربة حمار'],

  // ── food / drink
  food: ['طعام', 'اكل', 'أكل'],
  bread: ['خبز', 'عيش'],
  rice: ['ارز', 'أرز', 'رز'],
  meat: ['لحم'],
  beef: ['لحم بقر'],
  'cow meat': ['لحم بقر'],
  mutton: ['لحم ضأن'],
  'goat meat': ['لحم ماعز'],
  'chicken meat': ['لحم دجاج'],
  egg: ['بيض'],
  milk: ['حليب', 'لبن'],
  yogurt: ['زبادي', 'لبن'],
  butter: ['زبدة'],
  sugar: ['سكر'],
  salt: ['ملح'],
  flour: ['دقيق', 'طحين'],
  tea: ['شاي'],
  coffee: ['قهوة'],
  juice: ['عصير'],
  beverage: ['مشروب'],
  water: ['ماء', 'مية'],
  soup: ['شوربة', 'حساء'],
  apple: ['تفاح'],
  banana: ['موز'],
  bananas: ['موز'],
  mango: ['مانجو'],
  mangos: ['مانجو'],
  mangoes: ['مانجو'],
  grape: ['عنب'],
  grapes: ['عنب'],
  pomegranate: ['رمان'],
  watermelon: ['بطيخ'],
  melon: ['شمام'],
  pineapple: ['اناناس'],
  strawberry: ['فراولة'],
  guava: ['جوافة'],
  apricot: ['مشمش'],
  lemon: ['ليمون'],
  orange: ['برتقال'],
  fruit: ['فاكهة'],
  fruits: ['فواكه'],
  vegetables: ['خضار'],
  potato: ['بطاطس'],
  tomato: ['طماطم'],
  onion: ['بصل'],
  garlic: ['ثوم'],
  ginger: ['زنجبيل'],
  carrot: ['جزر'],
  cauliflower: ['قرنبيط'],
  cucumber: ['خيار'],
  spinach: ['سبانخ'],
  okra: ['بامية'],
  'lady finger': ['بامية'],
  brinjal: ['باذنجان'],
  aubergine: ['باذنجان'],
  eggplant: ['باذنجان'],
  radish: ['فجل'],
  coriander: ['كزبرة'],
  parsley: ['بقدونس'],
  'green chilli': ['فلفل اخضر'],
  'red chilli': ['فلفل احمر'],
  'sugar cane': ['قصب سكر'],
  sugarcane: ['قصب سكر'],
  noodles: ['نودلز'],
  burger: ['برجر'],
  cake: ['كيكة'],
  biscuit: ['بسكويت'],
  biscuits: ['بسكويت'],
  cookie: ['بسكويت'],
  cookies: ['بسكويت'],
  toffee: ['توفي'],
  candy: ['حلوى'],
  sweets: ['حلويات'],
  confectionery: ['حلويات'],
  'ice cream': ['ايس كريم'],
  icecream: ['ايس كريم'],
  jambul: ['جامبول'],
  jamun: ['جامبول'],
  'java plum': ['جامبول'],
  coconut: ['جوز هند'],
  chickpea: ['حمص'],
  lentil: ['عدس'],
  lentils: ['عدس'],
  feast: ['وليمة'],
  // Pakistani dishes — use phonetic Arabic
  naan: ['نان'],
  chapati: ['تشاباتي'],
  roti: ['روتي'],
  samosa: ['سمبوسة'],
  kebab: ['كباب'],
  'chana chaat': ['شانا تشات'],
  'dahi bhale': ['داهي باليه'],
  'dahi bhally': ['داهي باليه'],
  chicken: ['دجاج', 'فراخ'],
  chickpeas: ['حمص'],

  // ── animals
  dog: ['كلب'],
  doggy: ['كلب صغير'],
  cat: ['قطة'],
  cow: ['بقرة'],
  horse: ['حصان'],
  goat: ['ماعز'],
  sheep: ['خروف'],
  donkey: ['حمار'],
  camel: ['جمل'],
  lion: ['اسد', 'أسد'],
  lioness: ['لبؤة'],
  tiger: ['نمر'],
  elephant: ['فيل'],
  monkey: ['قرد'],
  rabbit: ['ارنب', 'أرنب'],
  bunny: ['ارنب صغير'],
  hare: ['ارنب بري'],
  rat: ['فأر'],
  mouse: ['فأر'],
  alligator: ['تمساح'],
  crocodile: ['تمساح'],
  fish: ['سمكة', 'سمك'],
  bird: ['طائر', 'عصفور'],
  hen: ['دجاجة'],
  rooster: ['ديك'],
  cock: ['ديك'],
  duck: ['بطة'],
  parrot: ['ببغاء'],
  pigeon: ['حمامة'],
  sparrow: ['عصفور'],
  owl: ['بومة'],
  peacock: ['طاووس'],
  crow: ['غراب'],
  raven: ['غراب'],
  frog: ['ضفدع'],
  toad: ['ضفدع'],
  tortoise: ['سلحفاة'],
  turtle: ['سلحفاة'],
  bandit: ['قاطع طريق'],
  giraffe: ['زرافة'],
  animal: ['حيوان'],

  // ── colors
  red: ['احمر', 'أحمر'],
  blue: ['ازرق', 'أزرق'],
  green: ['اخضر', 'أخضر'],
  greenish: ['مخضر'],
  yellow: ['اصفر', 'أصفر'],
  yellowish: ['مصفر'],
  black: ['اسود', 'أسود'],
  white: ['ابيض', 'أبيض'],
  brown: ['بني'],
  pink: ['وردي', 'بمبي'],
  purple: ['بنفسجي'],
  grey: ['رمادي'],
  gray: ['رمادي'],
  gold: ['ذهبي', 'دهب'],
  golden: ['ذهبي'],
  silver: ['فضي'],
  color: ['لون'],
  colour: ['لون'],
  complexion: ['بشرة'],
  pale: ['شاحب'],

  // ── body / health
  ill: ['مريض'],
  unwell: ['مريض'],
  sick: ['مريض'],
  ache: ['الم', 'ألم', 'وجع'],
  pain: ['الم', 'ألم'],
  medication: ['دواء'],
  medicine: ['دواء'],
  hospital_: ['مستشفى'],
  ambulance: ['اسعاف', 'إسعاف'],
  emergency: ['طوارئ'],
  physician: ['طبيب'],
  therapist: ['معالج'],
  // doctor not in dataset cleanly; map physician
  // ── feelings
  happy: ['سعيد', 'فرحان'],
  happiness: ['سعادة', 'فرح'],
  unhappy: ['حزين', 'مش مبسوط'],
  sad: ['حزين'],
  saddened: ['حزين'],
  saddening: ['محزن'],
  sadness: ['حزن'],
  sorrow: ['حزن'],
  sorrowful: ['حزين'],
  worry: ['قلق'],
  worried: ['قلقان'],
  anxiety: ['قلق'],
  anxious: ['قلقان'],
  anger: ['غضب'],
  angry: ['غاضب'],
  furious: ['غاضب جدا'],
  hate: ['كره'],
  hatred: ['كراهية'],
  loathe: ['يبغض'],
  loathing: ['بغض'],
  love: ['حب'],
  liked: ['اعجب'],
  liking: ['اعجاب'],
  like: ['يحب'],
  fondness: ['محبة'],
  joy: ['فرح'],
  fun: ['متعة'],
  enjoy: ['يستمتع'],
  enjoyable: ['ممتع'],
  entertaining: ['مسلي'],
  entertainment: ['تسلية'],
  fearsome: ['مخيف'],
  frightening: ['مخيف'],
  scary: ['مخيف'],
  terrifying: ['مرعب'],
  horrifying: ['مرعب'],
  shy: ['خجول'],
  shyness: ['خجل'],
  ashamed: ['مكسوف'],
  shame: ['عار', 'كسوف'],
  embarrassed: ['محرج'],
  embarrassing: ['محرج'],
  embarrassment: ['احراج'],
  humiliated: ['مهان'],
  humiliation: ['اهانة'],
  insult: ['اهانة'],
  insulted: ['مهان'],
  proud: ['فخور'],
  pride: ['فخر'],
  arrogant: ['متكبر'],
  arrogance: ['تكبر'],
  greed: ['طمع'],
  greedy: ['طماع'],
  miser: ['بخيل'],
  pinchpenny: ['بخيل'],
  stingy: ['بخيل'],
  cunning: ['ماكر'],
  clever: ['ذكي'],
  intelligent: ['ذكي'],
  intention: ['نية'],
  interested: ['مهتم'],
  interesting: ['مثير للاهتمام'],
  important: ['مهم'],
  honest: ['صادق'],
  honestly: ['بصدق'],
  honesty: ['صدق'],
  honourable: ['شريف'],
  decent: ['محترم'],
  obedient: ['مطيع'],
  obedience: ['طاعة'],
  obey: ['يطيع'],
  obstinacy: ['عناد'],
  stubborn: ['عنيد'],
  stubbornness: ['عناد'],
  punctual: ['ملتزم بالوقت'],
  punctuality: ['الالتزام بالوقت'],
  responsible: ['مسؤول'],
  responsibility: ['مسؤولية'],
  responsibly: ['بمسؤولية'],
  respect: ['احترام', 'إحترام'],
  respectful: ['محترم'],
  'well mannered': ['مؤدب'],
  brave: ['شجاع'],
  smart: ['ذكي'],
  stupid: ['غبي'],
  idiot: ['ابله'],
  idiotic: ['غبي'],
  fool: ['احمق'],
  foolish: ['احمق'],
  rascal: ['شقي'],
  scoundrel: ['وغد'],
  bully: ['متنمر'],
  cruel: ['قاسي'],
  cruelty: ['قسوة'],
  brutal: ['وحشي'],
  brutality: ['وحشية'],
  merciless: ['عديم الرحمة'],
  mercy: ['رحمة'],
  enemy: ['عدو'],
  enmity: ['عداوة'],
  animosity: ['عداوة'],
  hostility: ['عداوة'],
  rival: ['منافس'],
  rivalry: ['منافسة'],
  competition: ['منافسة'],
  competitiveness: ['تنافسية'],
  selfish: ['اناني', 'أناني'],
  selfishness: ['انانية'],
  patient: ['صبور'],
  calm: ['هادئ'],
  calmness: ['هدوء'],
  tranquility: ['هدوء'],
  'peace of mind': ['راحة بال'],
  relax: ['يسترخي'],
  relaxed: ['مسترخي'],
  relaxing: ['مريح'],
  rested: ['مرتاح'],
  resting: ['يرتاح'],
  restless: ['قلق'],
  restlessness: ['قلق'],
  joy_: ['فرح'],
  beautiful: ['جميل'],
  gorgeous: ['جميل جدا'],
  beauty: ['جمال'],
  handsome: ['وسيم'],
  pleasant: ['لطيف'],
  pleasing: ['ممتع'],
  delightful: ['ممتع'],
  good: ['جيد', 'كويس'],
  bad: ['سيء', 'وحش'],
  great: ['عظيم'],
  nice: ['لطيف'],
  rich: ['غني'],
  wealthy: ['غني'],
  wealth: ['ثروة'],
  poor: ['فقير'],
  impoverished: ['فقير'],
  poverty: ['فقر'],
  penniless: ['مفلس'],
  beggar: ['شحاذ'],
  mendicant: ['شحاذ'],
  laborer: ['عامل'],
  labourer: ['عامل'],
  servant: ['خادم'],
  maid: ['خادمة'],
  watchman: ['حارس'],
  staff: ['موظفون'],
  staff_: ['موظفون'],

  // ── verbs / common
  give: ['اعطي', 'أعطي', 'هات'],
  given: ['اعطى'],
  gave: ['اعطى'],
  take: ['خذ'],
  wait: ['انتظر', 'إنتظر'],
  waiting: ['انتظار'],
  go: ['اذهب', 'روح'],
  come: ['تعال'],
  walk: ['مشى', 'يمشي'],
  walking: ['يمشي'],
  stroll: ['يتمشى'],
  run: ['ركض', 'يجري'],
  sleep: ['نام', 'ينام'],
  wake: ['استيقظ', 'صحى'],
  'wake up': ['استيقظ'],
  awake: ['مستيقظ'],
  awaken: ['ايقظ'],
  awakened: ['استيقظ'],
  'waking up': ['الاستيقاظ'],
  see: ['ير', 'يشوف'],
  hear: ['سمع', 'يسمع'],
  speak: ['تكلم', 'يتكلم'],
  talk: ['تكلم', 'يتكلم'],
  conversation: ['محادثة'],
  listen: ['اسمع', 'استمع'],
  help: ['مساعدة', 'ساعد'],
  helpful: ['مفيد'],
  assistance: ['مساعدة'],
  aid: ['مساعدة'],
  benefit: ['فائدة'],
  beneficial: ['مفيد'],
  useful: ['مفيد'],
  usefulness: ['فائدة'],
  useless: ['عديم الفائدة'],
  utility: ['منفعة'],
  utilize: ['يستخدم'],
  use: ['استخدم'],
  usage: ['استخدام'],
  make: ['اصنع', 'يصنع'],
  made: ['صنع'],
  build: ['ابني', 'يبني'],
  built: ['بنى'],
  construct: ['ابني'],
  constructed: ['بنى'],
  manufacture: ['يصنع'],
  manufactured: ['مصنوع'],
  create: ['اخلق', 'يخلق'],
  created: ['خلق'],
  creator: ['الخالق'],
  initiate: ['ابدأ'],
  start: ['ابدأ', 'يبدأ'],
  started: ['بدأ'],
  starting: ['البدء'],
  begin: ['ابدأ'],
  began: ['بدأ'],
  begins: ['يبدأ'],
  begun: ['بدأ'],
  beginning: ['بداية'],
  end: ['نهاية'],
  final: ['نهائي'],
  first: ['اول', 'أول'],
  complete: ['كامل'],
  completed: ['اكتمل'],
  include: ['يشمل'],
  included: ['مشمول'],
  including: ['شامل'],
  includes: ['يشمل'],
  inclusive: ['شامل'],
  contain: ['يحتوي'],
  contained: ['محتوي'],
  containing: ['محتوي'],
  contains: ['يحتوي'],
  consist: ['يتكون'],
  find: ['ابحث', 'وجد'],
  search: ['بحث'],
  searched: ['بحث'],
  searching: ['يبحث'],
  loss: ['خسارة'],
  liberate: ['حرر'],
  liberated: ['محرر'],
  freed: ['حرر'],
  freedom: ['حرية'],
  independence: ['استقلال'],
  victory: ['نصر'],
  conquest: ['فتح'],
  defeat: ['هزيمة'],
  fail: ['فشل'],
  failed: ['فشل'],
  failure: ['فشل'],
  succeed: ['نجح'],
  succeeded: ['نجح'],
  success: ['نجاح'],
  successful: ['ناجح'],
  achievement: ['انجاز'],
  effort: ['جهد'],
  endeavor: ['سعي'],
  hard_: ['صعب'],
  hardship: ['مشقة'],
  difficult: ['صعب'],
  difficulty: ['صعوبة'],
  easy: ['سهل'],
  ease: ['سهولة'],
  easily: ['بسهولة'],
  easiness: ['سهولة'],
  hardwork: ['عمل شاق'],
  'hard work': ['عمل شاق'],
  'hard worker': ['مجتهد'],
  hardworking: ['مجتهد'],
  workout: ['تمرين'],
  exercise: ['تمرين'],
  // misc verbs
  forgive: ['سامح'],
  forgiveness: ['مغفرة'],
  pardon: ['عفو'],
  amnesty: ['عفو'],
  apology: ['اعتذار'],
  apologize: ['اعتذر'],
  approve: ['وافق'],
  approval: ['موافقة'],
  consent: ['موافقة'],
  permission: ['اذن', 'إذن'],
  pledge: ['تعهد'],
  pledged: ['تعهد'],
  promise: ['وعد'],
  promised: ['وعد'],
  preach: ['يبشر'],
  preaching: ['تبشير'],
  preachment: ['وعظ'],
  punish: ['عاقب'],
  punishment: ['عقاب'],
  penalty: ['عقوبة'],
  warn: ['حذر'],
  protect: ['حمى'],
  protected: ['محمي'],
  protection: ['حماية'],
  safe: ['امن', 'آمن'],
  safety: ['امان', 'أمان'],
  secure: ['امن'],
  security: ['امن'],
  'security guard': ['حارس امن'],

  // ── religion
  god: ['الله', 'رب'],
  allah: ['الله'],
  prophet: ['نبي'],
  apostle: ['رسول'],
  iblis: ['ابليس'],
  satan: ['شيطان'],
  devil: ['شيطان'],
  angel: ['ملاك'],
  paradise: ['جنة'],
  heaven: ['جنة'],
  hell: ['جحيم', 'نار'],
  faith: ['ايمان', 'إيمان'],
  belief: ['اعتقاد'],
  blessing: ['نعمة', 'بركة'],
  sin: ['ذنب'],
  fasting: ['صيام'],
  fast: ['صوم'],
  charity: ['صدقة'],
  zakat: ['زكاة'],
  pilgrimage: ['حج'],
  hajj: ['حج'],
  namaz: ['صلاة'],
  salat: ['صلاة'],
  prayer: ['صلاة'],
  fajr: ['فجر'],
  fajar: ['فجر'],
  zuhr: ['ظهر'],
  asr: ['عصر'],
  maghrib: ['مغرب'],
  isha: ['عشاء'],
  quran: ['قرآن', 'القرآن'],
  "qur'an": ['قرآن'],
  "holy qur'an": ['القرآن الكريم'],
  'holy quran': ['القرآن الكريم'],
  koran: ['قرآن'],
  quranic: ['قرآني'],
  hadith: ['حديث'],
  kalmah: ['كلمة'],
  imam: ['امام'],
  monotheism: ['توحيد'],
  monotheistic: ['موحد'],
  muslim: ['مسلم'],
  muslims: ['مسلمين'],
  christian: ['مسيحي'],
  christianity: ['مسيحية'],
  christians: ['مسيحيين'],
  hindu: ['هندوسي'],
  jihad: ['جهاد'],
  lunar: ['قمري'],
  solar: ['شمسي'],

  // ── school / work / things
  book: ['كتاب'],
  textbook: ['كتاب مدرسي'],
  newspaper: ['جريدة'],
  notebook: ['دفتر'],
  diary: ['مذكرة'],
  pen: ['قلم'],
  pencil: ['قلم رصاص'],
  ballpoint: ['قلم جاف'],
  'ballpoint pen': ['قلم جاف'],
  'ball point': ['قلم جاف'],
  'ball point pen': ['قلم جاف'],
  ink: ['حبر'],
  paper: ['ورق'],
  eraser: ['ممحاة'],
  sharpener: ['مبراة'],
  stapler: ['دباسة'],
  desk: ['مكتب'],
  chair: ['كرسي'],
  cupboard: ['دولاب'],
  closet: ['دولاب'],
  door: ['باب'],
  bell: ['جرس'],
  meter: ['متر'],
  'meter rod': ['عصا متر'],
  calculator: ['حاسبة'],
  calendar: ['تقويم'],
  schedule: ['جدول'],
  timetable: ['جدول'],
  bag: ['حقيبة', 'شنطة'],
  picture: ['صورة'],
  photo: ['صورة'],
  photograph: ['صورة'],
  image: ['صورة'],
  drama: ['دراما'],
  'drama serial': ['مسلسل'],
  'drama series': ['مسلسل'],
  movie: ['فيلم'],
  cartoon: ['كرتون'],
  cartoonish: ['كرتوني'],
  spectacle: ['نظارة'],
  camera: ['كاميرا'],
  bottle: ['زجاجة', 'قزازة'],
  glass: ['كوب'],
  cup: ['فنجان'],
  plate: ['طبق'],
  spoon: ['ملعقة'],
  knife: ['سكين'],
  brush: ['فرشاة'],
  comb: ['مشط'],
  soap: ['صابون'],
  towel: ['فوطة'],
  // clothing
  shoe: ['حذاء'],
  shoes: ['حذاء'],
  boots: ['بوت'],
  slippers: ['شبشب'],
  sandals: ['صندل'],
  dupatta: ['شال'],
  scarf: ['وشاح'],
  shirt: ['قميص'],
  kameez: ['قميص'],
  pajamas: ['بيجامة'],
  jeans: ['جينز'],
  'jeans pants': ['جينز'],
  'denim pants': ['جينز'],
  frock: ['فستان'],

  // ── school / work
  student: ['طالب'],
  teacher: ['معلم', 'مدرس'],
  professor: ['استاذ'],
  instructor: ['مدرس'],
  tutor: ['مدرس خصوصي'],
  apprentice: ['متدرب'],
  exam: ['امتحان'],
  examination: ['امتحان'],
  test: ['اختبار'],
  result: ['نتيجة'],
  question: ['سؤال'],
  answer: ['اجابة', 'إجابة'],
  answered: ['اجاب'],
  answering: ['يجيب'],
  knowledge: ['معرفة'],
  knowledgeable: ['عارف'],
  wise: ['حكيم'],
  illiteracy: ['امية', 'أمية'],
  illiterate: ['امي'],
  uneducated: ['غير متعلم'],
  science: ['علم'],
  scientific: ['علمي'],
  math: ['رياضيات'],
  maths: ['رياضيات'],
  mathematics: ['رياضيات'],
  art: ['فن'],
  arts: ['فنون'],
  poet: ['شاعر'],
  poetess: ['شاعرة'],
  poetry: ['شعر'],
  story: ['قصة'],
  tale: ['حكاية'],
  word: ['كلمة'],
  words: ['كلمات'],
  language: ['لغة'],
  urdu: ['اوردو'],
  // jobs
  job: ['وظيفة'],
  work: ['عمل', 'شغل'],
  worker: ['عامل'],
  business: ['اعمال', 'تجارة'],
  money: ['فلوس', 'مال', 'نقود'],
  loan: ['قرض'],
  debt: ['دين'],
  bribe: ['رشوة'],
  bribery: ['رشوة'],
  fraud: ['احتيال'],
  theft: ['سرقة'],
  thief: ['لص', 'حرامي'],
  robber: ['لص'],
  robbery: ['سرقة'],
  snatch: ['خطف'],
  snatched: ['اختطف'],
  dacoit: ['قاطع طريق'],
  gangster: ['عصابة'],
  rebel: ['متمرد'],
  rebellion: ['تمرد'],
  rebelliousness: ['تمرد'],
  revolt: ['ثورة'],
  mutiny: ['تمرد'],
  // government / politics
  government: ['حكومة'],
  governmental: ['حكومي'],
  govt: ['حكومة'],
  'prime minister': ['رئيس وزراء'],
  chairman: ['رئيس'],
  chairwoman: ['رئيسة'],
  chairperson: ['رئيس'],
  cheif: ['رئيس'],
  principal: ['ناظر'],
  principle: ['مبدأ'],
  attorney: ['محامي'],
  lawyer: ['محامي'],
  law: ['قانون'],
  legal: ['قانوني'],
  policeman: ['شرطي'],
  'police man': ['شرطي'],
  'police officer': ['ضابط شرطة'],
  'police woman': ['شرطية'],
  sepoy: ['جندي'],
  // farming / nature
  farmer: ['فلاح', 'مزارع'],
  irrigate: ['يروي'],
  irrigation: ['ري'],
  plants: ['نباتات'],
  tree: ['شجرة'],
  flower: ['زهرة', 'وردة'],
  leaf: ['ورقة'],
  seed: ['بذرة'],
  // misc abstract
  age: ['عمر'],
  birthday: ['عيد ميلاد'],
  wedding: ['عرس', 'زفاف'],
  marriage: ['زواج'],
  celebrate: ['احتفل'],
  celebration: ['احتفال'],
  parade: ['عرض'],
  procession: ['موكب'],
  process: ['عملية'],
  program: ['برنامج'],
  programme: ['برنامج'],
  programed: ['مبرمج'],
  system: ['نظام'],
  problem: ['مشكلة'],
  trouble: ['مشكلة'],
  defect: ['عيب'],
  defective: ['معيب'],
  damage: ['ضرر'],
  error: ['خطأ'],
  erroneous: ['خاطئ'],
  inaccurate: ['غير دقيق'],
  incorrect: ['غير صحيح'],
  mistake: ['خطأ'],
  mistaken: ['مخطئ'],
  wrong: ['خطأ'],
  truth: ['حقيقة'],
  true: ['صحيح'],
  truthful: ['صادق'],
  truthfully: ['بصدق'],
  false: ['كاذب'],
  falsehood: ['كذب'],
  untruth: ['كذب'],
  liar: ['كاذب'],
  defamation: ['تشهير'],
  defamed: ['مشوه السمعة'],
  disgrace: ['عار'],
  disgraced: ['مهان'],
  dishonoured: ['مهان'],
  backbiting: ['غيبة'],
  rumor: ['اشاعة'],
  rumour: ['اشاعة'],
  gossip: ['ثرثرة'],
  banter: ['مزاح'],
  joke: ['نكتة'],
  // states
  busy: ['مشغول'],
  preoccupied: ['مشغول'],
  idle: ['كسلان'],
  lazy: ['كسلان'],
  laziness: ['كسل'],
  lazily: ['بكسل'],
  'work-shy': ['كسلان'],
  'work dodger': ['كسلان'],
  workshy: ['كسلان'],
  weak: ['ضعيف'],
  weaker: ['اضعف'],
  weakness: ['ضعف'],
  fit: ['لائق'],
  fitness: ['لياقة'],
  cool: ['بارد', 'كول'],
  chill: ['برد'],
  chilled: ['مبرد'],
  chilly: ['بارد'],
  full: ['ممتلئ'],
  empty: ['فارغ'],
  noise: ['ضوضاء'],
  noisy: ['مزعج'],
  nonsense: ['هراء'],
  pointless: ['بلا فائدة'],
  futile: ['عبثي'],
  senseless: ['بلا معنى'],
  absurd: ['سخيف'],
  // direction / position
  in: ['في'],
  at: ['في'],
  on: ['على'],
  to: ['الى', 'إلى'],
  from: ['من'],
  with: ['مع'],
  and: ['و'],
  but: ['لكن'],
  or: ['او', 'أو'],
  // misc adjectives
  ahead: ['امام', 'أمام'],
  forward: ['الى الامام'],
  away: ['بعيد'],
  far: ['بعيد'],
  'far away': ['بعيد جدا'],
  near: ['قريب'],
  nearby: ['قريب'],
  middle: ['وسط'],
  center: ['مركز'],
  centre: ['مركز'],
  between: ['بين'],
  along: ['مع'],
  inside: ['داخل'],
  outside: ['خارج'],
  front: ['امام'],
  // sizes
  big: ['كبير'],
  small: ['صغير'],
  large: ['كبير'],
  long: ['طويل'],
  short: ['قصير'],
  high: ['عالي'],
  low: ['منخفض'],
  thick: ['سميك'],
  thin: ['نحيف'],
  // etc.
  new: ['جديد'],
  old: ['قديم'],
  young: ['شاب'],
  many: ['كثير'],
  few: ['قليل'],
  some: ['بعض'],
  all: ['كل'],
  every_: ['كل'],
  more: ['اكثر', 'أكثر'],
  less: ['اقل', 'أقل'],
  // misc verbs/feelings
  desire: ['رغبة'],
  wish: ['امنية'],
  hope: ['امل', 'أمل'],
  luck: ['حظ'],
  fate: ['مصير', 'قدر'],
  hurry: ['عجلة'],
  haste: ['عجلة'],
  quick: ['سريع'],
  quickly: ['بسرعة'],
  rapidly: ['بسرعة'],
  speedy: ['سريع'],
  swiftly: ['بسرعة'],
  sudden: ['مفاجئ'],
  suddenly: ['فجأة'],
  surely: ['بالتأكيد'],
  definitely: ['بالتأكيد'],
  perhaps: ['ربما'],
  maybe: ['ربما'],
  indeed: ['فعلا'],
  certainly: ['بالتأكيد'],
  // misc nouns
  thirst: ['عطش'],
  thirsty: ['عطشان'],
  hungry: ['جوعان', 'جائع'],
  hunger: ['جوع'],
  // duties / tasks
  duty: ['واجب'],
  task: ['مهمة'],
  responsibility_: ['مسؤولية'],
  // services
  attention: ['انتباه'],
  focus: ['تركيز'],
  consider: ['اعتبر'],
  consideration: ['اعتبار'],
  suggestion: ['اقتراح'],
  advice: ['نصيحة'],
  information: ['معلومات'],
  // misc
  population: ['سكان'],
  social: ['اجتماعي'],
  society: ['مجتمع'],
  ethnic: ['عرقي'],
  ethnicity: ['عرق'],
  history: ['تاريخ'],
  'historic places': ['اماكن تاريخية'],
  'historic sites': ['مواقع تاريخية'],
  // misc verbs
  vote: ['صوت'],
  voting: ['تصويت'],
  election: ['انتخابات'],
  elections: ['انتخابات'],
  count: ['عد'],
  measure: ['قياس'],
  build_: ['ابني'],
  // adjectives
  hot_: ['حار'],
  cold_: ['بارد'],
  fast: ['سريع'],
  slow: ['بطيء'],
  same: ['نفس'],
  different: ['مختلف'],
  various: ['متنوع'],
  all_: ['كل'],
  // misc kitchen
  charcoal: ['فحم'],
  coal: ['فحم'],
  // currency / saudi etc — keep
  saudi: ['سعودي'],
  'saudi arabia': ['السعودية'],
  'saudi arabian': ['سعودي'],
  iran: ['ايران', 'إيران'],
  iranian: ['ايراني'],
  iraq: ['العراق'],
  iraqi: ['عراقي'],
  india: ['الهند'],
  indian: ['هندي'],
  hindustan: ['الهند'],
  bangladesh: ['بنجلاديش'],
  afghanistan: ['افغانستان'],
  australia: ['استراليا'],
  australian: ['استرالي'],
  china: ['الصين'],
  japan: ['اليابان'],
  japanese: ['ياباني'],
  england: ['انجلترا'],
  america: ['امريكا'],
  'united states of america': ['الولايات المتحدة الامريكية'],
  usa: ['امريكا'],
  kuwait: ['الكويت'],
  dubai: ['دبي'],
  // misc
  watermelon_: ['بطيخ'],
  // generic
  exhibit: ['معرض'],
  exhibition: ['معرض'],
  alarm: ['منبه'],
  drink: ['شرب', 'مشروب'],
  beverage_: ['مشروب'],
  // body
  air: ['هواء'],
  earth_: ['ارض'],
  // misc
  amen: ['آمين'],
  // legacy "where" — not in PSL, skip
  // ── interrogatives & misc small words handled above
};

// Build output
const lines = [];
const used = new Set();
for (const [en, arabicForms] of Object.entries(T)) {
  // strip the underscore disambiguators we used to dedupe key conflicts
  const enClean = en.replace(/_$/, '');
  for (const ar of arabicForms) {
    const key = ar.trim();
    if (!key || used.has(key)) continue;
    used.add(key);
    lines.push(`  '${key}': '${enClean}',`);
  }
}
console.log(lines.length + ' Arabic forms covering ' + Object.keys(T).length + ' English tokens');
fs.writeFileSync(__dirname + '/../arabic_map.dart', lines.join('\n'));
console.log('Written: arabic_map.dart');
